alpha: 0.5
batchsize: 64
dataset: cifar10
embed_dim: 128
gausblur: false
imgsize: 32
lr: 0.0003
maxepochs: -1
modelarch: resnet
ncoeff: 0.7
nsamples: 40000
numworkers: 20
omega: 0.0
optimizer: adam
pflip: true
ro: 1.0
s: 0.5
scheduler: false
simmetric: gaussian
sinv: 16000000.0
sinv_init_coeff: 2.0
titer: 1000000
valsplit: 0.2
xi: 0.0
